### ISSUE TITLE
Missing college - UTS03

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/AuditDataSteward#12]
Please add the primary_program_id to the output, so we know which programs are missing_colleges.

Two different issues found. One a student is showing a missing college, but that student  is not enrolled: 

00198697 | Kami | Jones
-- | -- | --

One student is showing a missing college, but has a primary program of MSN-NSLD and academic programs shows a college for MSN-NSLD, so not sure why it is showing missing.

00296657 | Whitney | Goudjil
-- | -- | --

**Comment by JoyLindsay** [comment]
I am closing this issue as completed, if it is still an issue we should reopen/revisit it in ut-effectiveness.
